In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 3  # Vectorized operation
print(result)

[  1   8  27  64 125]


In [7]:
result + 10 # this is using Broadcasting
# using SIMD (Single Instruction, Multiple Data)

array([ 11,  18,  37,  74, 135])

In [8]:
arr1 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


In [11]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print("Normalized Data:\n", normalized_data)

Normalized Data:
 [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
