In [2]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [5]:
flatten = arr.flatten()
print(flatten)

[1 2 3 4 5 6 7 8 9 0]


In [6]:
flatten[:2]

array([1, 2])

In [8]:
flatten[::2]

array([1, 3, 5, 7, 9])

In [10]:
flatten[::5]

array([1, 6])

In [12]:
arr[0][:3]

array([1, 2, 3])

In [13]:
arr[1][3:]

array([9, 0])

In [15]:
arr2 = flatten[:5]
arr2

array([1, 2, 3, 4, 5])

In [16]:
arr2[0] = 100
flatten

array([100,   2,   3,   4,   5,   6,   7,   8,   9,   0])

In [19]:
flatten[flatten>6] # Boolean masking

array([100,   7,   8,   9])

## Excercise for Today
 - Create a 3×3 array filled with random numbers and print its shape.
 - Convert an array of floats [1.1, 2.2, 3.3] into integers.
 - Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
 - Reshape a 1D array of size 9 into a 3×3 matrix.
 - Use boolean masking to filter numbers greater than 50 in an array.

In [24]:
#1 
array3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape =",array3x3.shape)

Shape = (3, 3)


In [30]:
#2 
arrfloat = np.array([1.1, 2.2, 3.3], dtype=np.int64)
arrfloat

array([1, 2, 3])

In [36]:
#3
arrfancy = np.array([1, 2, 3, 4, 5, 6])
arrfancy[[1,3,5]]

array([2, 4, 6])

In [39]:
#4
array1D = np.array([1,3,3,2,5,2,3,24,32])
array1D.reshape(3,3)

array([[ 1,  3,  3],
       [ 2,  5,  2],
       [ 3, 24, 32]])

In [41]:
#5
array50 = np.array([42,54,4,5,5,3,35,43,56,435,4,6,6,5,6,54])
array50[array50>50]

array([ 54,  56, 435,  54])