In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr[0, 2]

np.int64(3)

In [5]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [9]:
arr[:2, :2]

array([[1, 2],
       [4, 5]])

In [15]:
print(np.sum(arr[:], axis=1)) # Sum all row values meaning
print(np.sum(arr[:], axis=0)) # Sum all column values meaning

[ 6 15 24]
[12 15 18]


In [6]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
 
# Output of arr3D.shape is -> (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [7]:
arr3D[:,0,:2]

array([[1, 2],
       [7, 8]])